name: Excel Sync

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Sync
        run: python sync.py
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          ESBFILE_ID: ${{ secrets.ESBFILE_ID }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Save last sync state
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add last_sync.txt
          git commit -m "Update last sync time" || echo "No changes to commit"
          git push
